In [1]:
def vander_input(x,N,order):
    X=x.size
    result_array = np.empty((N,X),dtype=int)
    if order.upper()=='True':
        for i in range(N):
            power_vector=np.array(np.power(x,i))
            result_array[i]=power_vector
    else:
        for i in range(N-1,-1,-1):
            power_vector=np.array(np.power(x,i))
            result_array[(N-1)-i]=power_vector
    return result_array        

In [2]:
import numpy as np
print('Generate a vandermode matrix')
N=int(input('Enter the value of N power:'))
print('Enter comma separated list of elements(1,2,3..):')
input_vector=input()
input_list=list(map(int,input_vector.split(',')))
x=np.array(input_list)
print('Input vector is:')
print(x)
order=input("Enter 'True' for increasing order of powers else enter'False'")
result_array=vander_input(x,N,order)
print('The resultant vandermode matrix:')
print(result_array.T)

Generate a vandermode matrix
Enter the value of N power:4
Enter comma separated list of elements(1,2,3..):
1,2,3,4,5
Input vector is:
[1 2 3 4 5]
Enter 'True' for increasing order of powers else enter'False'True
The resultant vandermode matrix:
[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]]
